name: failing-test-workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run a test command
        run: |
          echo "Dieser Test schlägt absichtlich fail"
          exit 1