name: s-fail-test-workflow

on:
  workflow_run:
    workflows: ["a-seconde-test-workflow"]
    types:
      - completed

jobs:
  fail-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run failing test
        run: |
          echo "Dieser Test schlägt absichtlich fehl!"
          exit 1  # Fehler erzwingen
