name: a-seconde-test-workflow

on:
  workflow_run:
    workflows: ["test-workflow"]  
    types:
      - completed  

jobs:
  second-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run second test
        run: echo "Hello from Second Test!"
